// test/noHardcodedVersion.test.js
// Guards the global constraint in docs/plans/2026-08-21-release-infrastructure.md:
// package.json and the generated buildInfo.json are the only places a version number
// is allowed to live. Every other copy is a number someone has to remember to bump,
// which is exactly the drift docs/design/aether-convergence-plan.md describes -- the
// footer, the docs and package.json disagreeing about which build this is.
//
// The allowlist below is the point of the test as much as the scan is. Some hits are
// legitimate: prose about a version that shipped in the past is a historical fact, not
// a value that should track HEAD. Those get an entry with a written reason, so being
// exempt is a decision someone made rather than a pattern that happened not to match.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

// CHANGELOG.md is out of scope by omission, not oversight: like buildInfo.json it is
// generated by the release step, and every version heading in it is a historical fact.
const ROOT = path.join(__dirname, '..');
const SCAN_DIRS = ['src', 'docs'];
const SCAN_FILES = ['README.md', 'CLAUDE.md'];

// Binary assets (docs/images) have no version literals to find and cannot be read as
// text, so the scan is opt-in by extension rather than opt-out by directory.
const TEXT_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.md', '.html', '.css', '.yml', '.yaml']);

// A dotted triple that is not part of a longer dotted run: 127.0.0.1 is an address and
// 2026.08.29.1 is not a version, so neither may match. The optional prerelease tag is
// consumed as part of the literal so 2.0.0-alpha.0 is reported once, whole, rather than
// as a bare 2.0.0 with trailing noise the reader has to reassemble.
const SEMVER = /(?<![\w.])\d+\.\d+\.\d+(?:-[0-9A-Za-z][0-9A-Za-z.-]*)?(?![\w.])/g;

// { file, literal, reason } -- exempts every occurrence of that literal in that file.
// Omit `literal` to exempt the whole file, which is the right shape for a dated record:
// its entire job is to say what was true on the day it was written, so there is no
// individual number in it that should ever be bumped.
//
// A reason is required: an entry without one is indistinguishable from a hit nobody
// looked at.
const ALLOWLIST = [
  // --- Illustrative payloads: someone else's version number, not this app's. ---
  {
    file: 'src/main/latestVersionReader.js',
    literal: '2.2.0',
    reason:
      'Example latest.json payload in the module doc comment. That file is published by whoever cuts a build, so the number is a sample of a remote document, not a claim about this build.',
  },
  {
    file: 'src/shared/versionCheck.js',
    literal: '2.1.7',
    reason:
      'Sample inputs documenting which version strings the parser accepts. Genericising them would delete the comment\'s only content -- the literal forms are the point.',
  },
  {
    file: 'README.md',
    literal: '2.2.0',
    reason:
      'Same example latest.json payload as latestVersionReader.js, shown to whoever has to hand-publish that file.',
  },

  // --- Dated records: history, not state. Bumping these would falsify them. ---
  {
    file: 'docs/follow-ups.md',
    reason:
      'Findings log. Each entry records the version the finding was observed at; rewriting those numbers would make the log describe a session that never happened.',
  },
  {
    file: 'docs/design/2026-08-05-app-move-and-aether-reskin.md',
    reason: 'Dated design doc -- a record of the dependency set decided on that date.',
  },
  {
    file: 'docs/design/aether-convergence-plan.md',
    reason:
      'Design doc whose worked examples are about version drift itself, including the 0.1.2-vs-0.1.3 case this very test was written to prevent.',
  },
  {
    file: 'docs/plans/2026-08-04-packages-core-extraction.md',
    reason: 'Dated plan -- a record of the versions in play when it was written.',
  },
  {
    file: 'docs/plans/2026-08-04-shared-folder-version-check.md',
    reason: 'Dated plan; its examples are version-comparison test fixtures.',
  },
  {
    file: 'docs/plans/2026-08-05-app-move-phases-0-2.md',
    reason: 'Dated plan -- quotes the package.json of the day, dependency pins included.',
  },
  {
    file: 'docs/plans/2026-08-13-reskin-phase-5-slices.md',
    reason: 'Dated plan -- pins a playwright-core version used for a one-off screenshot run.',
  },
  {
    file: 'docs/prototype/index.html',
    reason:
      'Frozen HTML prototype. Its hard-coded 2.1.7 is mock data for a static mockup with no build behind it; the real app reads buildInfo.json.',
  },
];

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (TEXT_EXTENSIONS.has(path.extname(entry.name))) out.push(full);
  }
  return out;
}

function scanTargets() {
  const fromDirs = SCAN_DIRS
    .map((d) => path.join(ROOT, d))
    .filter((d) => fs.existsSync(d))
    .flatMap((d) => walk(d, []));
  const fromFiles = SCAN_FILES
    .map((f) => path.join(ROOT, f))
    .filter((f) => fs.existsSync(f));
  return [...fromDirs, ...fromFiles];
}

function isAllowed(relPath, literal) {
  return ALLOWLIST.some(
    (e) => e.file === relPath && (e.literal === undefined || e.literal === literal)
  );
}

function findVersionLiterals() {
  const hits = [];
  for (const file of scanTargets()) {
    const rel = path.relative(ROOT, file).split(path.sep).join('/');
    const lines = fs.readFileSync(file, 'utf8').split(/\r?\n/);
    lines.forEach((line, i) => {
      for (const match of line.matchAll(SEMVER)) {
        if (isAllowed(rel, match[0])) continue;
        hits.push(`${rel}:${i + 1}: ${match[0]}  --  ${line.trim().slice(0, 100)}`);
      }
    });
  }
  return hits;
}

test('no version literal outside package.json and the generated buildInfo.json', () => {
  const hits = findVersionLiterals();
  assert.deepStrictEqual(
    hits,
    [],
    `version literals found -- fix them, or add an ALLOWLIST entry with a reason:\n${hits.join('\n')}`
  );
});

test('every allowlist entry names a file that still exists', () => {
  const missing = ALLOWLIST
    .filter((e) => !fs.existsSync(path.join(ROOT, e.file)))
    .map((e) => e.file);
  assert.deepStrictEqual(missing, [], `allowlist entries point at files that are gone:\n${missing.join('\n')}`);
});

test('every allowlist entry carries a written reason', () => {
  const unreasoned = ALLOWLIST
    .filter((e) => typeof e.reason !== 'string' || e.reason.trim().length === 0)
    .map((e) => `${e.file}: ${e.literal}`);
  assert.deepStrictEqual(unreasoned, [], `allowlist entries without a reason:\n${unreasoned.join('\n')}`);
});
